spring:
  datasource:
    url: jdbc:h2:tcp://192.168.219.100/~/yaksa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
