spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/yaksa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
